<?php

declare(strict_types=1);

return [
    'dictionary' => [
        ['name' => 'Anh', 'element' => 'moc', 'gender' => 'unisex', 'meaning' => 'Thông minh, sáng dạ, nổi bật.'],
        ['name' => 'Bách', 'element' => 'moc', 'gender' => 'male', 'meaning' => 'Vững chãi như cây bách, sống bền chí.'],
        ['name' => 'Lâm', 'element' => 'moc', 'gender' => 'male', 'meaning' => 'Khu rừng lớn, biểu tượng sinh sôi mạnh mẽ.'],
        ['name' => 'Tùng', 'element' => 'moc', 'gender' => 'male', 'meaning' => 'Kiên cường, chính trực qua mọi hoàn cảnh.'],
        ['name' => 'Đăng', 'element' => 'moc', 'gender' => 'male', 'meaning' => 'Vươn cao, tiến bộ, nhiều khát vọng.'],
        ['name' => 'Thảo', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Hiền hòa, gần gũi và giàu sức sống.'],
        ['name' => 'Mai', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Thanh tao, trong sáng và may mắn.'],
        ['name' => 'Lan', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Dịu dàng, thanh khiết và quý phái.'],
        ['name' => 'Vy', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Nhỏ nhắn, đáng yêu và kiên cường.'],
        ['name' => 'Trúc', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Thanh cao, mềm dẻo nhưng bền bỉ.'],
        ['name' => 'Nam', 'element' => 'moc', 'gender' => 'male', 'meaning' => 'Vững vàng, chính trực và bền bỉ.'],
        ['name' => 'Phương', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Thanh nhã, ngay thẳng và tinh tế.'],
        ['name' => 'Cẩm', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Đẹp đẽ, duyên dáng và thanh cao.'],
        ['name' => 'Quỳnh', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Nhã nhặn, quý phái và dịu dàng.'],
        ['name' => 'Gia Linh', 'element' => 'moc', 'gender' => 'female', 'meaning' => 'Thông minh, mềm mại, đem lại sinh khí.'],

        ['name' => 'Linh', 'element' => 'hoa', 'gender' => 'unisex', 'meaning' => 'Nhanh nhạy, linh hoạt, sáng trí.'],
        ['name' => 'Minh', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Sáng suốt, công minh, có trí tuệ.'],
        ['name' => 'Nhật', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Mặt trời, nguồn năng lượng tích cực.'],
        ['name' => 'Huy', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Rực rỡ, thành đạt, tỏa sáng.'],
        ['name' => 'Dũng', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Dũng cảm, quyết đoán và trách nhiệm.'],
        ['name' => 'Diễm', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Duyên dáng, rạng rỡ, thu hút.'],
        ['name' => 'Ánh', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Ánh sáng, mang niềm vui và hy vọng.'],
        ['name' => 'Hân', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Vui tươi, mang nguồn năng lượng ấm áp.'],
        ['name' => 'Nhiên', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Tự nhiên, hồn hậu, giàu nhiệt tâm.'],
        ['name' => 'Tâm', 'element' => 'hoa', 'gender' => 'unisex', 'meaning' => 'Tấm lòng ấm áp, chân thành, nhân ái.'],
        ['name' => 'Tuấn', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Khôi ngô, sáng dạ và quyết đoán.'],
        ['name' => 'Thiên Ân', 'element' => 'hoa', 'gender' => 'male', 'meaning' => 'Ân huệ trời ban, sáng rõ và may mắn.'],
        ['name' => 'Bích', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Tươi sáng, quý phái và tinh anh.'],
        ['name' => 'Ngân Hà', 'element' => 'hoa', 'gender' => 'female', 'meaning' => 'Rực rỡ như dải ngân hà, đầy sức sống.'],
        ['name' => 'Hoài An', 'element' => 'hoa', 'gender' => 'unisex', 'meaning' => 'Nồng ấm, an hòa và nhiều thiện ý.'],

        ['name' => 'Giang', 'element' => 'thuy', 'gender' => 'unisex', 'meaning' => 'Dòng sông hiền hòa, linh hoạt.'],
        ['name' => 'Khánh', 'element' => 'thuy', 'gender' => 'unisex', 'meaning' => 'Niềm vui, điềm lành, may mắn.'],
        ['name' => 'Vũ', 'element' => 'thuy', 'gender' => 'male', 'meaning' => 'Mưa thuận hòa, giàu cảm xúc.'],
        ['name' => 'Hải', 'element' => 'thuy', 'gender' => 'male', 'meaning' => 'Biển lớn, bao dung và sâu rộng.'],
        ['name' => 'Phong', 'element' => 'thuy', 'gender' => 'male', 'meaning' => 'Phóng khoáng, linh hoạt, giàu biến hóa.'],
        ['name' => 'Hà', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Dòng nước mát, dịu dàng.'],
        ['name' => 'Thủy', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Mềm mại, sâu sắc và tinh tế.'],
        ['name' => 'Yến', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Nhẹ nhàng, uyển chuyển, duyên dáng.'],
        ['name' => 'Lam', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Màu xanh dịu mát, tinh tế và thanh nhã.'],
        ['name' => 'An Nhiên', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Bình thản, thư thái, an hòa.'],
        ['name' => 'Duy', 'element' => 'thuy', 'gender' => 'male', 'meaning' => 'Tinh tế, mềm dẻo và sâu sắc.'],
        ['name' => 'Bình Minh', 'element' => 'thuy', 'gender' => 'male', 'meaning' => 'Nguồn sinh khí mới, hài hòa và sáng rõ.'],
        ['name' => 'Uyên', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Sâu sắc, thông tuệ, dịu dàng.'],
        ['name' => 'Tuyết', 'element' => 'thuy', 'gender' => 'female', 'meaning' => 'Tinh khôi, nhẹ nhàng và trong trẻo.'],
        ['name' => 'Khả Hân', 'element' => 'thuy', 'gender' => 'unisex', 'meaning' => 'Vui tươi, điềm tĩnh và giàu cảm xúc tốt đẹp.'],

        ['name' => 'An', 'element' => 'tho', 'gender' => 'unisex', 'meaning' => 'Bình an, ổn định, hài hòa.'],
        ['name' => 'Sơn', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Vững vàng, đáng tin cậy như núi.'],
        ['name' => 'Khoa', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Học thức, tiến bộ và thành đạt.'],
        ['name' => 'Kiên', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Bền chí, chắc chắn, đáng tin cậy.'],
        ['name' => 'Quân', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Chững chạc, bản lĩnh, có trách nhiệm.'],
        ['name' => 'Trang', 'element' => 'tho', 'gender' => 'female', 'meaning' => 'Đoan trang, chính trực, nền nã.'],
        ['name' => 'Bình', 'element' => 'tho', 'gender' => 'unisex', 'meaning' => 'Yên ổn, cân bằng, hòa thuận.'],
        ['name' => 'Hiền', 'element' => 'tho', 'gender' => 'female', 'meaning' => 'Hiền hậu, nền nã và đức độ.'],
        ['name' => 'Thư', 'element' => 'tho', 'gender' => 'female', 'meaning' => 'Trang nhã, điềm đạm và sâu sắc.'],
        ['name' => 'Bảo An', 'element' => 'tho', 'gender' => 'unisex', 'meaning' => 'Bình an quý giá, gia đạo yên vui.'],
        ['name' => 'Vĩnh', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Bền vững, ổn định và trường tồn.'],
        ['name' => 'Đức', 'element' => 'tho', 'gender' => 'male', 'meaning' => 'Chuẩn mực, đáng tin và giàu nhân nghĩa.'],
        ['name' => 'Nhã', 'element' => 'tho', 'gender' => 'female', 'meaning' => 'Nhẹ nhàng, nền nã và hài hòa.'],
        ['name' => 'Gia Hân', 'element' => 'tho', 'gender' => 'female', 'meaning' => 'Niềm vui trong gia đình, cân bằng và ấm êm.'],
        ['name' => 'Thiện', 'element' => 'tho', 'gender' => 'unisex', 'meaning' => 'Lành tính, hiền hòa và vững tâm.'],

        ['name' => 'Bảo', 'element' => 'kim', 'gender' => 'unisex', 'meaning' => 'Báu vật, được yêu thương và trân quý.'],
        ['name' => 'Ngọc', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Quý giá, trong sáng, tinh anh.'],
        ['name' => 'Kim', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Giá trị, kiên định và sắc sảo.'],
        ['name' => 'Châu', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Viên ngọc quý, thanh lịch và sâu sắc.'],
        ['name' => 'Quang', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'Ánh sáng, chính trực và thành công.'],
        ['name' => 'Phúc', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'May mắn, phúc đức và sung túc.'],
        ['name' => 'Khôi', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'Tuấn tú, sáng dạ, nổi bật.'],
        ['name' => 'Thành', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'Thành tựu, vững chắc và bản lĩnh.'],
        ['name' => 'Thanh', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Trong sáng, thanh cao, tinh tế.'],
        ['name' => 'Diệu', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Tinh anh, sâu sắc, đầy duyên lành.'],
        ['name' => 'Tín', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'Uy tín, chính trực, đáng tin cậy.'],
        ['name' => 'Cường', 'element' => 'kim', 'gender' => 'male', 'meaning' => 'Mạnh mẽ, dứt khoát và bản lĩnh.'],
        ['name' => 'Thùy', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Nết na, mềm mại và thanh lịch.'],
        ['name' => 'Bích Ngọc', 'element' => 'kim', 'gender' => 'female', 'meaning' => 'Viên ngọc quý, tinh tế và trong sáng.'],
        ['name' => 'Gia Bảo', 'element' => 'kim', 'gender' => 'unisex', 'meaning' => 'Báu vật của gia đình, quý giá và vững vàng.'],
    ],

    'middle_names' => [
        'male' => [
            'default' => ['Gia', 'Hoàng', 'Minh', 'Quốc', 'Thiên', 'Đức', 'Hữu', 'Anh', 'Tấn'],
            'kim' => ['Bảo', 'Anh', 'Công'],
            'moc' => ['Đăng', 'Xuân', 'Nhật', 'Văn'],
            'thuy' => ['Hải', 'Trường', 'Nguyên', 'Thanh'],
            'hoa' => ['Huy', 'Dương', 'Quang', 'Nhật'],
            'tho' => ['Trung', 'Phúc', 'Khánh', 'Gia'],
        ],
        'female' => [
            'default' => ['Ngọc', 'Khánh', 'Tú', 'Diễm', 'Thanh', 'Bảo', 'Gia', 'Như', 'Quỳnh'],
            'kim' => ['Minh', 'Kim', 'Bích', 'Gia'],
            'moc' => ['Mai', 'Thảo', 'Trúc', 'Cẩm'],
            'thuy' => ['Hà', 'Lam', 'Yên', 'Tuyết'],
            'hoa' => ['Ánh', 'Hồng', 'Diệu', 'Ngân'],
            'tho' => ['An', 'Hiền', 'Nhã', 'Gia'],
        ],
    ],
];
